[package]
name = "lance-jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lance = { path="../../rust/lance" }
arrow = { features = ["ffi"] }
tokio = { version = "1.23", features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "sync",
] }
jni = "0.21.1"
snafu = "0.7.4"
